config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tickers#index'

  resources :admin, only: [:index]

  namespace :admin do
    resources :tickers do
      resources :comments, only: [:index, :show, :destroy]
    end
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :pages
    resources :terms
  end

  resources :tickers do
    resources :comments
  end

  resources :terms
  resources :pages

  get "search", to: "search#search"

end

app/views/admin/pages/edit.html.erb
<head>
<title>Admin Panel - Edit Page</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Edit <%= @page.title %></h1>
  <%= form_for [@page], method: :patch do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, size: "50" %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "50x8" %>
  </p>
  <p>
    <%= f.label :advantages %><br />
    <%= f.text_area :advantages, size: "50x6" %>
  </p>
  <p>
    <%= f.label :warnings %><br />
    <%= f.text_area :warnings, size: "50x6" %>
  </p>
  <%= f.submit "Submit" %>
  <% end %>
  </center

app/views/admin/pages/index.html.erb
<head>
  <title>Admin Panel - Pages Index</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Pages Admin Panel</h1>
  <p><h2><%= link_to "Submit New Page", new_admin_page_path %></h2></p>
  <table>
  <col width="250">
  <col width="50">
  <col width="50">
  <% @pages.each do |page| %>
  <tr>
    <td><%= link_to page.title, page_path(page) %></td>
    <td><%= link_to "Edit", edit_admin_page_path(page) %></td>
    <td><%= link_to "Delete", admin_page_path(page), method: :delete %></td>
  </tr>
  <% end %>
  </table>
</center>

app/views/admin/pages/new.html.erb
<head>
  <title>Admin Panel - Submit New Page</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Submit New Page</h1>
<%= form_for [@page] do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, size: "50" %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "50x8" %>
  </p>
  <p>
    <%= f.label :advantages %><br />
    <%= f.text_area :advantages, size: "50x6" %>
  </p>
  <p>
    <%= f.label :warnings %><br />
    <%= f.text_area :warnings, size: "50x6" %>
  </p>
    <%= f.submit "Submit" %>
<% end %>
</center