config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tickers#index'

  resources :admin, only: [:index]

  namespace :admin do
    resources :tickers do
      resources :comments, only: [:index, :show, :destroy]
    end
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :pages
    resources :terms
  end

  resources :tickers do
    resources :comments
  end

  resources :terms
  resources :pages

  get "search", to: "search#search"

end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
  validates :symbol, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :sector, presence: true
  validates :price, presence: true
  validates :daily_change, presence: true
  validates :market_cap, presence: true
  validates :volume, presence: true
  validates :mov_avg_50, presence: true
  validates :mov_avg_50_cmp, presence: true
  validates :high_52, presence: true
  validates :high_52, presence: true

  has_many :comments

  def self.search(query)
    where("symbol ilike ? or name ilike ?", "%#{query}%", "%#{query}%")
  end
end

app/controllers/admin/tickers_controller.rb
class Admin::TickersController < ApplicationController
  before_action :check_admin

  def check_admin
    if !current_user.admin
      redirect_to root_path, notice: "The URL you just attempted to access is for website administrators only."
    end
  end

  def index
    @tickers = Ticker.order(name: :asc)
  end

  def edit
    @ticker = Ticker.find(params[:id])
  end
end

app/controllers/tickers_controller.rb
require 'open-uri'
require 'uri'

class TickersController < ApplicationController
  def index
    $sp_data = open(URI.encode("http://download.finance.yahoo.com/d/quotes.csv?s=^GSPC&f=l1,c")).read.split(",")
    $nasdaq_data = open(URI.encode("http://download.finance.yahoo.com/d/quotes.csv?s=^IXIC&f=l1,c")).read.split(",")
    @tickers = Ticker.search(params[:q]).order("symbol DESC")
    @nasdaq_price = $nasdaq_data[0].to_f.round(1)
    @nasdaq_change = $nasdaq_data[2].split(" - ")[1].to_f
    @sp_price = $sp_data[0].to_f.round(1)
    @sp_change = $sp_data[2].split(" - ")[1].to_f
  end

  def show
    @ticker = Ticker.find(params[:id])
    @comment = Comment.new
    @comments = @ticker.comments.order("created_at ASC").page(params[:page]).per(25)
  end

  def update
    @ticker = Ticker.find(params[:id])
    if @ticker.update(ticker_params)
      redirect_to ticker_path(@ticker), notice: "Ticker successfully edited."
    end
  end

  def ticker_params
    params.require(:ticker).permit(:symbol, :name, :market_cap, :pe, :peb)
  end
end

app/views/tickers/index.html.erb
<head>
  <title>MarketHack</title>
  <script src="jquery-1.11.1.min.js"></script>
</head>

<div style="text-align: right; display: inline-block; float:right">
  <%= form_for search_path, method: :get do |f| %>
    <%= f.label "Stock Search:", :class => 'search_label' %>
    <%= text_field_tag :q, params[:q], :class => 'search_field' %>
    <%= button_tag "Search", name: nil, :class => 'search_button' %>
  <% end %>
</div>

<% if params[:q] and params[:q] != "" %>
  <%= link_to "Back to Home Page", root_path %>
  <br />
  <center><h2>Search Results for "<%= params[:q] %>"</h2>
  <% if @tickers %>
    <% @tickers.each do |ticker| %>
      <br />
      <%= link_to "#{ticker.symbol} (#{ticker.name})", ticker_path(ticker)%>
      <br />
    <% end %>
  <% end %>
  </center><br />

<% else %>
<div id="index-stats">
  <table style="font-weight: bold">
    <col width="150">
    <col width="200">
    <tr>
      <td class="center">NASDAQ</td>
      <td class="nasdaq"><%= number_with_delimiter(@nasdaq_price,  :precision => 1, :delimiter => ',') %>
        (<% if @nasdaq_change >= 0 %>↑<% end %><%= @nasdaq_change %>%)</td>
      <% if @nasdaq_change >= 0 %>
        <script>$(".nasdaq").addClass("green")</script>
      <% else %>
        <script>$(".nasdaq").addClass("red")</script>
      <% end %>
    </tr>
    <tr>
      <td class="center">S&P 500</td>
      <td class="sp"><%= number_with_delimiter(@sp_price,  :precision => 1, :delimiter => ',') %>
        (<% if @sp_change >= 0 %>↑<% end %><%= @sp_change %>%)</td>
        <% if @sp_change >= 0 %>
          <script>$(".sp").addClass("green")</script>
        <% else %>
          <script>$(".sp").addClass("red")</script>
        <% end %>
    </tr>
  </table>
</div>

<center><h1>Stocks by Movement</h1></center>
<div class="display_table" style="clear: left">
  <div class="table-head"><%= link_to "Active Stocks (by Volume)", page_path(Page.find_by(title: "Active Stocks (by Volume)")) %></div>
    <table>
      <col width="120">
      <col width="60">
      <col width="60">
      <col width="120">
      <tr>
        <th>Ticker</th>
        <th colspan="2">Price</th>
        <th>Volume</th>
      </tr>
      <% Ticker.order(volume_cmp: :desc).limit(4).each do |ticker| %>
      <tr>
        <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
        <td class="right"><%= ticker.price %> </td>
        <td><span class=<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>>(<%= ticker.daily_change %>%)</span></td>
        <td class="center"><%= ticker.volume %>M <font size="1px">(avg. <%= ticker.volume_avg %>M)</font></td>
      </tr>
      <% end %>
    </table>
</div>

<div class="display_table">
  <div class="table-head"><%= link_to "Active Stocks (by Price Change)", page_path(Page.find_by(title: "Active Stocks (by Price Change)")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Volume</th>
    </tr>
    <% Ticker.order(daily_change_abs: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %></td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.volume %>M <font size="1px">(avg. <%= ticker.volume_avg %>M)</font></td>
    </tr>
    <% end %>
  </table>
</div>

<div class="display_table">
  <div class="table-head"><%= link_to "Value Stocks", page_path(Page.find_by(title: "Value Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="60">
    <col width="60">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>P/E</th>
      <th>P/B</th>
    </tr>
    <% Ticker.order(pe_peb_avg: :asc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %></td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><% if ticker.pe %><%= ticker.pe %><% else %>--<% end %></td>
      <td class="center"><%= ticker.peb %></td>
    </tr>
    <% end %>
  </table>
</div>


<div class="display_table">
  <div class="table-head"><%= link_to "Momentum Stocks", page_path(Page.find_by(title: "Momentum Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="60">
    <col width="60">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th colspan="2">50-Day M.A.</th>
    </tr>
    <% Ticker.order(mov_avg_50_cmp: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %></td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="right"><%= ticker.mov_avg_50 %></td>
      <td><span class="<% if ticker.mov_avg_50_cmp >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.mov_avg_50_cmp %>%)</span></td>
    </tr>
    <% end %>
  </table>
</div>

<div class="display_table">
  <div class="table-head"><%= link_to "Volatile Stocks", page_path(Page.find_by(title: "Volatile Stocks")) %></div>
  <table>
    <col width="120">
    <col width="50">
    <col width="50">
    <col width="50">
    <col width="110">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>β</th>
      <th>52W Range</th>
    </tr>
    <% Ticker.where("daily_change_abs > ?", 1).order(daily_annual_change_avg: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.beta %></td>
      <td>(<%= ticker.low_52 %> - <%= ticker.high_52 %>)</td>
    </tr>
    <% end %>
  </table>
</div>

<div class="display_table">
  <div class="table-head"><%= link_to "Small Cap Stocks", page_path(Page.find_by(title: "Small Cap Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="60">
    <col width="60">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Cap</th>
      <th>P/E</th>
    </tr>
    <% Ticker.where("market_cap_num < ?", 5000000000).order(daily_change_abs: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %></td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
      <td class="center"><% if ticker.pe %><%= ticker.pe %><% else %>--<% end %></td>
    </tr>
    <% end %>
  </table>
</div>

<center><h1 style="clear: both"><br />Stocks by Sector</h1></center>
<div class="display_table">
  <div class="table-head"><%= link_to "Tech (Strong Performers)", page_path(Page.find_by(title: "Tech Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Tech").order(daily_change: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="display_table">
  <div class="table-head"><%= link_to "Finance (Strong Performers)", page_path(Page.find_by(title: "Finance Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Finance").order(daily_change: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="display_table">
  <div class="table-head"><%= link_to "Energy (Strong Performers)", page_path(Page.find_by(title: "Energy Stocks")) %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Energy").order(daily_change: :desc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<br />
<div class="display_table">
  <div class="table-head"><%= link_to "Tech (Weak Performers)", page_path(Page.find_by(title: "Tech Stocks"), anchor: "bottom") %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Tech").order(daily_change: :asc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="display_table">
  <div class="table-head"><%= link_to "Finance (Weak Performers)", page_path(Page.find_by(title: "Finance Stocks"), anchor: "bottom") %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Finance").order(daily_change: :asc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="display_table">
  <div class="table-head"><%= link_to "Energy (Weak Performers)", page_path(Page.find_by(title: "Energy Stocks"), anchor: "bottom") %></div>
  <table>
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="120">
    <tr>
      <th>Ticker</th>
      <th colspan="2">Price</th>
      <th>Market Cap</th>
    </tr>
    <% Ticker.where("sector = ?", "Energy").order(daily_change: :asc).limit(4).each do |ticker| %>
    <tr>
      <td><%= link_to ticker.symbol, ticker_path(ticker) %> <font size="1px">(<%= ticker.name %>)</font></td>
      <td class="right"><%= ticker.price %> </td>
      <td><span class="<% if ticker.daily_change >= 0 %> <%= "green" %> <% else %> <%= "red" %> <% end %>">(<%= ticker.daily_change %>%)</span></td>
      <td class="center"><%= ticker.market_cap %></td>
    </tr>
    <% end %>
  </table>
</div>
<br />
<% end %>

app/views/tickers/show.html.erb
<head>
  <title>MarketHack - <%= @ticker.symbol %> (<%= @ticker.name %>) Ticker</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script src="http://code.highcharts.com/stock/highstock.js"></script>
  <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
</head>

<%= link_to 'Back to Home Page', root_path %>

<center><h1>
  <%= @ticker.symbol %> (<%= @ticker.name %>)
</h1></center>

<div id="ticker-stats">
  <center>
    Price: $<span class="pt40"><%= @ticker.price %></span>
    <span class="pt20 daily_change"> (<%= @ticker.daily_change %>%)</span>
  </center>
      <% if @ticker.daily_change >= 0 %>
        <script>$(".daily_change").addClass("green");</script>
      <% else %>
        <script>$(".daily_change").addClass("red");</script>
      <% end %>
  <hr />
  <center><%= link_to "Market Cap", term_path(Term.find_by(name: "Market Cap")) %>: $
    <% if @ticker.market_cap %>
      <span style="font-size: 30pt">
        <%= @ticker.market_cap %>
      </span>
      <span style="font-size: 15pt">
        <% if @ticker.market_cap_num > 50000000000 %> (Large Cap)
        <% elsif @ticker.market_cap_num > 5000000000 %> (Mid Cap)
        <% else %> (Small Cap)
        <% end %>
      </span>
    <% end %>
  <hr />
  <center>
    <%= link_to "P/E", term_path(Term.find_by(name: "P/E")) %>:
    <span class="pt30">
      <% if @ticker.pe %> <%= @ticker.pe %>
      <% else %> --
      <% end %>
    </span>
  </center>
    <span id="pe_comment">
      <% if @ticker.pe.nil? %>
        (This company is not profitable. Investment requires confidence that this company can get out of the red.)
        <script>$("#pe_comment").addClass("red");</script>
      <% elsif @ticker.pe <= 12 and @ticker.sector != 'Finance' or @ticker.pe <= 10 %>
        (This stock has a low P/E, meaning that the market expects little growth for this company. For stable, well-run companies capable of sustained future growth, a low P/E may imply undervaluation.)
        <script>$("#pe_comment").addClass("green");</script>
      <% elsif @ticker.pe >= 30 %>
        (A high P/E means the market expects rapid profit expansion. If the company doesn't meet these expectations, shares could fall sharply. )
        <script>$("#pe_comment").addClass("red");</script>
      <% end %>
    </span>
  <hr />
  <center>
    <%= link_to "P/B", term_path(Term.find_by(name: "P/B")) %>: <span style="font-size: 30pt"><%= @ticker.peb %></span>
  </center>
    <span class="pb_comment">
      <% if @ticker.peb <= 1 and @ticker.sector != 'Finance' or @ticker.peb <= 0.8 %>
        (This stock is selling below book value, meaning that its cash and physical assets (minus debt) are worth more than the stock.)
        <script>$(".pb_comment").addClass("green");</script>
      <% end %>
    </span>
  <hr />
  <center>
    <%= link_to "50-Day Moving Average", term_path(Term.find_by(name: "50-Day Moving Average")) %>: <span class="pt30"><%= @ticker.mov_avg_50 %></span>
    <span class="pt20 ma50_cmp"> (<%= @ticker.mov_avg_50_cmp %>%) </span>
      <% if @ticker.mov_avg_50_cmp >= 0 %>
        <script>$(".ma50_cmp").addClass("green");</script>
      <% else %>
        <script>$(".ma50_cmp").addClass("red");</script>
      <% end %>
  </center>
    <span class="ma50_comment">
      <% if @ticker.mov_avg_50_cmp >= 5 %>
        (This stock has been moving upward lately, and may be a good candidate for a momentum play.)
        <script>$(".ma50_comment").addClass("green");</script>
      <% elsif @ticker.mov_avg_50_cmp <= -5 %>
        (This stock has been moving down lately. Take caution.)
        <script>$(".ma50_comment").addClass("red");</script>
      <% end %>
    </span>
  <hr />
  <center>
    52 Week Range:
    <span class="pt30"><%= @ticker.low_52 %> - <%= @ticker.high_52 %></span>
  </center>
    <% if @ticker.daily_annual_change_avg > 500 %>(This stock is very high volatility. Approach with caution.)<% end %>
</div>

<div id="container"></div>

<% if !Rails.env.test? %>
  <%= content_for :extra_footer do %>
    <script>
    $(document).ready(function () {

      $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=?', function (data) {

        $('#container').highcharts('StockChart', {

          rangeSelector : {
            selected : 1
          },

          title : {
            text : 'Stock Price'
          },

          series : [{
            name : 'Price',
            data : data,
            tooltip: {
              valueDecimals: 2
            }
          }]
        });
      });

      if(document.URL.indexOf("#")==-1){
        url = document.URL+"#";
        location = "#";
        location.reload(true);
      }

    });
    </script>
  <% end %>
<% end %>

<div id="comments-div">

  <center><h1>
    Comments (<%= Comment.where(ticker_id: @ticker.id).count %>)
  </h1></center>
  <br />
  <% if @comments %>
    <%= paginate @comments %>
    <% @comments.each do |comment| %>
      <center>
        <div id="comment-outer">
          <div id="comment-description">
            <%= comment.description %><br />
          </div>
          <hr />
          <div id="comment-info">
            <% if current_user == User.find(comment.user_id) or current_user.admin %>
              <span class="pt10"><%= link_to "Edit", edit_ticker_comment_path(@ticker, comment) %> | <%= link_to "Delete", ticker_comment_path(@ticker, comment), method: :delete %> | </span>
            <% end %>
            <span class="pt7">Submitted by:</span> <%= User.find(comment.user_id).email %><br />
            <span class="pt7">Created on:</span> <%= (comment.created_at.to_s)[0..10] %>
            <span class="pt7">at</span> <%= (comment.created_at.to_s)[11..15] %>
            <span class="pt7">with Stock Price at</span> <%= comment.stock_price %>
            <span class="comment_cmp">(<%= ((1-comment.stock_price/@ticker.price)*100).round %>%)</span>
            <% if comment.stock_price/@ticker.price >= 1 %>
              <script>$(".comment_cmp").addClass("green");</script>
            <% else %>
              <script>$(".comment_cmp").addClass("red");</script>
            <% end %>
          </div>
        </div>
      </center>
    <% end %>
  <% end %>

  <div style="margin: 50px 20px">
    <% if @comment != nil and @comment.errors.any? %>
      <h3 class="red"><%= pluralize(@comment.errors.count, "error") %> prohibited this question from being saved.<br />
      Please enter a comment under 500 characters long.</h3>
    <% end %>
  </div>

  <center><h3><%= "Add a comment about #{@ticker.name}"  %></h3></center>
  <%= form_for [@ticker, @comment] do |f| %>
    <center>
      <div class="description">
        <%= f.text_area :description, size: "50x10" %>
      <br />
      </div>
      Please keep your comment to under 500 characters.<br /><br />
      <div class="rating">
        <%= f.submit  "Submit"%>
      </div>
    </center>
  <% end %>

</div>