config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tickers#index'

  resources :admin, only: [:index]

  namespace :admin do
    resources :tickers do
      resources :comments, only: [:index, :show, :destroy]
    end
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :pages
    resources :terms
  end

  resources :tickers do
    resources :comments
  end

  resources :terms
  resources :pages

  get "search", to: "search#search"

end

app/models/term.rb
class Term < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/admin/terms_controller.rb
class Admin::TermsController < ApplicationController
  before_action :check_admin

  def check_admin
    if !current_user.admin
      redirect_to root_path, notice: "The URL you just attempted to access is for website administrators only."
    end
  end

  def index
    @terms = Term.order(name: :asc)
  end

  def edit
    @term = Term.find(params[:id])
  end

  def destroy
    @term = Term.find(params[:id])
    if @term.destroy
      redirect_to admin_terms_path, notice: "Page successfully deleted."
    end
  end

  def new
    @term = Term.new
  end
end

app/controllers/concerns/terms_controller.rb
class TermsController < ApplicationController
  def index
    @terms = Term.order(name: :asc)
  end

  def update
    @term = Term.find(params[:id])
    if @term.update(term_params)
      redirect_to admin_terms_path
    end
  end

  def create
    @term = Term.new(term_params)
    if @term.save
      redirect_to admin_terms_path
      flash[:notice] = "Page successfully added."
    end
  end

  def term_params
    params.require(:term).permit(:name, :definition, :example)
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def show
    @term = Term.find(params[:id])
  end

  def create
    @term = Term.new(term_params)
    if @term.save
      redirect_to term_path(@term), notice: "Term successfully added."
    end
  end

  def update
    @term = Term.find(params[:id])
    if @term.update(term_params)
      redirect_to term_path(@term), notice: "Term successfully edited."
    end
  end

  def term_params
    params.require(:term).permit(:name, :definition, :example)
  end
end

app/views/admin/terms/edit.html.erb
<head>
  <title>Admin Panel - Edit Term</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Edit <%= @term.name %></h1>
  <%= form_for [@term], method: :patch do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, size: "50" %>
  </p>
  <p>
    <%= f.label :definition %><br />
    <%= f.text_area :definition, size: "50x8" %>
  </p>
  <p>
    <%= f.label :example %><br />
    <%= f.text_area :example, size: "50x6" %>
  </p>
  <%= f.submit "Submit" %>
  <% end %>
</center>

app/views/admin/terms/index.html.erb
<head>
  <title>Admin Panel - Terms Index</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Terms Admin Panel</h1>
  <p><h2><%= link_to "Submit New Term", new_admin_term_path %></h2></p>
  <table>
    <col width="250">
    <col width="50">
    <col width="50">
    <% @terms.each do |term| %>
    <tr>
      <td><%= link_to term.name, term_path(term) %></td>
      <td><%= link_to "Edit", edit_admin_term_path(term) %></td>
      <td><%= link_to "Delete", admin_term_path(term), method: :delete %></td>
    </tr>
    <% end %>
  </table>
</center>

app/views/admin/terms/new.html.erb
<head>
  <title>Admin Panel - Submit New Page</title>
</head>
<%= link_to "Back to Admin Panel", admin_index_path %>
<center>
  <h1>Submit New Page</h1>
  <%= form_for [@term] do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, size: "50" %>
  </p>
  <p>
    <%= f.label :definition %><br />
    <%= f.text_area :definition, size: "50x8" %>
  </p>
  <p>
    <%= f.label :example %><br />
    <%= f.text_area :example, size: "50x6" %>
  </p>
  <%= f.submit "Submit" %>
  <% end %>
  </center